### ISSUE TITLE
Add ActiveGate tolerations

### ISSUE THREAD

**Issue by mihaly-farkas** [mihaly-farkas/cdk8s-dynatrace-kubernetes-monitoring#9]
Enhance the DynaKube configuration with add default values for [.spec.activeGate / tolerations](https://docs.dynatrace.com/docs/ingest-from/setup-on-k8s/reference/dynakube-parameters)

The below YAML should be added:
```yaml
tolerations:
  - key: node-role.kubernetes.io/master
    operator: Exists
    effect: NoSchedule
```
